export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIE_RECOMMEND = 'GET_MOVIE_RECOMMEND';
export const SET_MOVIE_RECOMMEND = 'SET_MOVIE_RECOMMEND';
export const SET_USER_MOVIE_RECOMMEND = 'SET_USER_MOVIE_RECOMMEND';
export const SET_MOVIE_GENRES = 'SET_MOVIE_GENRES';

export const TOGGLE_SPINNER = 'TOGGLE_SPINNER';

export const SET_FILTER = 'SET_FILTER';
export const SORT_BY_YEAR = 'SORT_BY_YEAR';
export const SORT_BY_RATING = 'SORT_BY_RATING';

export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERR = 'AUTH_ERR';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';

export const GET_REVIEWS = 'GET_REVIEWS';
export const SET_REVIEWS = 'SET_REVIEWS';
export const UPDATE_REVIEWS = 'UPDATE_REVIEWS';
export const ADD_REVIEW = 'ADD_REVIEW';
export const REVIEW_LOADING = 'REVIEW_LOADING';
export const SET_MODAL_OPEN = 'SET_MODAL_OPEN';

export const SET_MOVIE_SEARCH = 'SET_MOVIE_SEARCH';
export const SET_ADVANCED_SEARCH_SORT_BY = 'SET_ADVANCED_SEARCH_SORT_BY';
export const SET_ADVANCED_SEARCH_FILTER_BY = 'SET_ADVANCED_SEARCH_FILTER_BY';
export const ADVANCED_SEARCH_LOADING = 'ADVANCED_SEARCH_LOADING';
export const SET_ADVANCED_SEARCH_RESULT = 'SET_ADVANCED_SEARCH_RESULT';